//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SchoolSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERP_SchoolSystemEntities : DbContext
    {
        public ERP_SchoolSystemEntities()
            : base("name=ERP_SchoolSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CboDepartment> CboDepartments { get; set; }
        public virtual DbSet<CboDesignation> CboDesignations { get; set; }
        public virtual DbSet<CboEmpStatu> CboEmpStatus { get; set; }
        public virtual DbSet<TblCity> TblCities { get; set; }
        public virtual DbSet<TblCountry> TblCountries { get; set; }
        public virtual DbSet<TblEmpEduDetail> TblEmpEduDetails { get; set; }
        public virtual DbSet<TblEmpExpDetail> TblEmpExpDetails { get; set; }
        public virtual DbSet<TblEmployee> TblEmployees { get; set; }
        public virtual DbSet<TblProvince> TblProvinces { get; set; }
        public virtual DbSet<TblSchool> TblSchools { get; set; }
        public virtual DbSet<TblSchoolBranch> TblSchoolBranches { get; set; }
        public virtual DbSet<TblSchoolMonthlyPayment> TblSchoolMonthlyPayments { get; set; }
        public virtual DbSet<TblSchoolPackage> TblSchoolPackages { get; set; }
        public virtual DbSet<TblUserType> TblUserTypes { get; set; }
    }
}
