//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SchoolSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERP_SchoolSystemEntities : DbContext
    {
        public ERP_SchoolSystemEntities()
            : base("name=ERP_SchoolSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CboDepartment> CboDepartments { get; set; }
        public virtual DbSet<CboDesignation> CboDesignations { get; set; }
        public virtual DbSet<CboEmpStatu> CboEmpStatus { get; set; }
        public virtual DbSet<CboStd_Guardian_Income> CboStd_Guardian_Income { get; set; }
        public virtual DbSet<CboStd_Guardian_Occupation> CboStd_Guardian_Occupation { get; set; }
        public virtual DbSet<CboStd_Guardian_Relationship> CboStd_Guardian_Relationship { get; set; }
        public virtual DbSet<CboStudyProgram> CboStudyPrograms { get; set; }
        public virtual DbSet<GLAccount> GLAccounts { get; set; }
        public virtual DbSet<GLDetailAccount> GLDetailAccounts { get; set; }
        public virtual DbSet<GLMainGroup> GLMainGroups { get; set; }
        public virtual DbSet<GLMajorAccount> GLMajorAccounts { get; set; }
        public virtual DbSet<Tbl_School_Classes_Setup> Tbl_School_Classes_Setup { get; set; }
        public virtual DbSet<Tbl_School_Fee_Setup> Tbl_School_Fee_Setup { get; set; }
        public virtual DbSet<Tbl_School_Std_Fee> Tbl_School_Std_Fee { get; set; }
        public virtual DbSet<Tbl_School_Std_Monthly_Fee> Tbl_School_Std_Monthly_Fee { get; set; }
        public virtual DbSet<Tbl_Std_Details> Tbl_Std_Details { get; set; }
        public virtual DbSet<Tbl_Std_Last_School_Details> Tbl_Std_Last_School_Details { get; set; }
        public virtual DbSet<Tbl_Std_Last_School_Document_Details> Tbl_Std_Last_School_Document_Details { get; set; }
        public virtual DbSet<Tbl_StudyProgram> Tbl_StudyProgram { get; set; }
        public virtual DbSet<TblCity> TblCities { get; set; }
        public virtual DbSet<TblCountry> TblCountries { get; set; }
        public virtual DbSet<TblEmpEduDetail> TblEmpEduDetails { get; set; }
        public virtual DbSet<TblEmpExpDetail> TblEmpExpDetails { get; set; }
        public virtual DbSet<TblEmployee> TblEmployees { get; set; }
        public virtual DbSet<TblProvince> TblProvinces { get; set; }
        public virtual DbSet<TblSchool> TblSchools { get; set; }
        public virtual DbSet<TblSchoolBranch> TblSchoolBranches { get; set; }
        public virtual DbSet<TblSchoolBranchesFee> TblSchoolBranchesFees { get; set; }
        public virtual DbSet<TblSchoolFee> TblSchoolFees { get; set; }
        public virtual DbSet<TblSchoolMonthlyPayment> TblSchoolMonthlyPayments { get; set; }
        public virtual DbSet<TblSchoolPackage> TblSchoolPackages { get; set; }
        public virtual DbSet<TblUserType> TblUserTypes { get; set; }
    }
}
