//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SchoolSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Std_Details
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public int SchoolID { get; set; }
        public Nullable<int> UserID { get; set; }
        public int BranchID { get; set; }
        public bool IsActive { get; set; }
        public string StudentName { get; set; }
        public string FatherName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string CNIC { get; set; }
        public string Contact { get; set; }
        public string Home_Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> P_ProvincesID { get; set; }
        public Nullable<int> P_CityID { get; set; }
        public string P_Address { get; set; }
        public Nullable<int> R_ProvincesID { get; set; }
        public Nullable<int> R_CityID { get; set; }
        public string R_Address { get; set; }
        public string G_Name { get; set; }
        public string G_ContactPrimary { get; set; }
        public Nullable<int> G_Releationship { get; set; }
        public Nullable<int> G_CountryID { get; set; }
        public Nullable<int> G_ProvincesID { get; set; }
        public Nullable<int> G_CityID { get; set; }
        public string G_Address { get; set; }
        public Nullable<int> G_Occupation { get; set; }
        public Nullable<int> G_MonthlyIncome { get; set; }
        public string G_ContactSecoundary { get; set; }
        public string G_WorkContact { get; set; }
        public string G_Email { get; set; }
        public string G_CNIC { get; set; }
        public string Std_BatchNo { get; set; }
        public string Std_BatchDetails { get; set; }
        public string Std_RollNo { get; set; }
        public int Std_Study_ProgramID { get; set; }
        public string Std_DocDetails { get; set; }
        public byte[] Std_Picture { get; set; }
        public string ProfilePicturePath { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> ModifyOn { get; set; }
        public Nullable<int> ModifyBy { get; set; }
    }
}
