//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SchoolSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_School_Std_Monthly_Fee
    {
        public int ID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> FeeID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<double> FeeAmount { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> StudentFee { get; set; }
        public Nullable<double> RecivedAmount { get; set; }
        public Nullable<System.DateTime> ReceivedOn { get; set; }
        public Nullable<int> ReceivedBy { get; set; }
        public string FeeMonth { get; set; }
        public Nullable<int> FeeYear { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyOn { get; set; }
    }
}
