//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SchoolSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEmpEduDetail
    {
        public int ID { get; set; }
        public int EmpID { get; set; }
        public string DegreeTitle { get; set; }
        public string InstituteName { get; set; }
        public string DegreeCompletionYear { get; set; }
        public string Remarks { get; set; }
    
        public virtual TblEmployee TblEmployee { get; set; }
    }
}
