//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SchoolSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblEmployee()
        {
            this.TblEmpEduDetails = new HashSet<TblEmpEduDetail>();
            this.TblEmpExpDetails = new HashSet<TblEmpExpDetail>();
        }
    
        public int EmpID { get; set; }
        public string EmpCode { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string HusbandName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string MaritalStatus { get; set; }
        public string CNIC { get; set; }
        public string Email { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> ProvincesID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string HomeAddress { get; set; }
        public string Contact1 { get; set; }
        public string Contact2 { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public string NTNNo { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string JobDescription { get; set; }
        public string DutyLocation { get; set; }
        public string BankAccountNo { get; set; }
        public Nullable<bool> TaxFiler { get; set; }
        public Nullable<double> IncomeTax { get; set; }
        public byte[] EmpPicture { get; set; }
        public string ProfilePicturePath { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifidOn { get; set; }
    
        public virtual CboDepartment CboDepartment { get; set; }
        public virtual CboDesignation CboDesignation { get; set; }
        public virtual CboEmpStatu CboEmpStatu { get; set; }
        public virtual TblCity TblCity { get; set; }
        public virtual TblCountry TblCountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEmpEduDetail> TblEmpEduDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEmpExpDetail> TblEmpExpDetails { get; set; }
        public virtual TblProvince TblProvince { get; set; }
        public virtual TblSchool TblSchool { get; set; }
    }
}
