//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SchoolSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSchoolFee
    {
        public int ID { get; set; }
        public int SchoolID { get; set; }
        public Nullable<int> PackageID { get; set; }
        public Nullable<double> MonthFee { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual TblSchool TblSchool { get; set; }
        public virtual TblSchoolPackage TblSchoolPackage { get; set; }
    }
}
