//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SchoolSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSchoolBranchesFee
    {
        public int ID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> PackageID { get; set; }
        public string Percentage { get; set; }
        public Nullable<double> MonthlyFee { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> ModifyOn { get; set; }
        public Nullable<int> ModifyBy { get; set; }
    
        public virtual TblSchool TblSchool { get; set; }
        public virtual TblSchoolBranch TblSchoolBranch { get; set; }
        public virtual TblSchoolPackage TblSchoolPackage { get; set; }
    }
}
