//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SchoolSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSchool
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblSchool()
        {
            this.CboDepartments = new HashSet<CboDepartment>();
            this.CboDesignations = new HashSet<CboDesignation>();
            this.CboEmpStatus = new HashSet<CboEmpStatu>();
            this.Tbl_StudyProgram = new HashSet<Tbl_StudyProgram>();
            this.TblEmployees = new HashSet<TblEmployee>();
            this.TblSchoolBranches = new HashSet<TblSchoolBranch>();
            this.TblSchoolBranchesFees = new HashSet<TblSchoolBranchesFee>();
            this.TblSchoolFees = new HashSet<TblSchoolFee>();
            this.TblSchoolMonthlyPayments = new HashSet<TblSchoolMonthlyPayment>();
        }
    
        public int SchoolId { get; set; }
        public string SchoolName { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public string Address { get; set; }
        public string RegistrationNo { get; set; }
        public string NTNNo { get; set; }
        public string PtclNo { get; set; }
        public string CellNo { get; set; }
        public string CellNo1 { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string SROfficerName { get; set; }
        public string SROffiersContactNo { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBY { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> ModifeidDateTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public byte[] SchoolLogo { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string AdminUserName { get; set; }
        public string SchoolShortCode { get; set; }
        public string SchoolLogoPath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CboDepartment> CboDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CboDesignation> CboDesignations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CboEmpStatu> CboEmpStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_StudyProgram> Tbl_StudyProgram { get; set; }
        public virtual TblCity TblCity { get; set; }
        public virtual TblCountry TblCountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEmployee> TblEmployees { get; set; }
        public virtual TblProvince TblProvince { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSchoolBranch> TblSchoolBranches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSchoolBranchesFee> TblSchoolBranchesFees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSchoolFee> TblSchoolFees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSchoolMonthlyPayment> TblSchoolMonthlyPayments { get; set; }
    }
}
